### ISSUE TITLE
Define a design scheme for our app

### ISSUE THREAD

**Issue by cbchien** [chingu-voyage3/bears-24#10]
User Story:

**As a** user,
**I want to** see a consist color scheme 
**so that I can** have a comfortable user experience and a vibrant visual experience

Acceptance Criteria:
- [x] Color scheme: Define choice of colors to be used in design for the Big Calendar App
- [x] Font scheme: Define three font family for the Big Calendar App

Examples and resources:
https://coolors.co/f79256-fbd1a2-7dcfb6-00b2ca-1d4e89
http://paletton.com/#uid=1000u0kllllaFw0g0qFqFg0w0aF

**Comment by GlynL** [comment]
# Color Scheme

/* Palette generated by Material Palette - materialpalette.com/teal/cyan */

.dark-primary-color    { background: #00796B; }
.default-primary-color { background: #009688; }
.light-primary-color   { background: #B2DFDB; }
.text-primary-color    { color: #FFFFFF; }
.accent-color          { background: #00BCD4; }
.primary-text-color    { color: #212121; }
.secondary-text-color  { color: #757575; }
.divider-color         { border-color: #BDBDBD; }

**Comment by GlynL** [comment]
# Font Scheme

## Nunito - Google Font
* 400 regular
* 400 italic
* 700 bold

### link
`<link href="https://fonts.googleapis.com/css?family=Nunito:400,400i,700" rel="stylesheet">`

### CSS Rule
`font-family: 'Nunito', sans-serif;`

**Comment by cbchien** [comment]
Nice Work!
