### ISSUE TITLE
Define Event schema

### ISSUE THREAD

**Issue by cbchien** [chingu-voyage3/bears-24#12]
User Story:

**As a** admin,
**I want to** have a data schema for storing Event information and data 
**so that I can** have a consistent data structure to read and update event database

Acceptance Criteria:
- [x] event title
- [x] date
- [x] description
- [x] RSVP list
- [x] participant capacity
- [x] cost
- [ ] other fields that you think will be required/useful

Examples and resources:
https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-1
https://docs.mongodb.com/v3.4/core/data-model-design/

**Comment by cbchien** [comment]
Task completed. Merged pull request #15

**Comment by GlynL** [comment]
merge request #16
